apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-refresh
  namespace: spring-dev
spec:
  schedule: "0 * * * *" # 1시간마다 실행
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-access-sa
          containers:
          - name: ecr-secret-refresh
            image: shinnyriver/kubectl-awscli:latest
            command: [ "/bin/sh", "-c" ]
            args:
            - |
              echo "Refreshing ECR Secret..."
              TOKEN=$(aws ecr get-login-password --region ap-northeast-2)
              kubectl create secret docker-registry ecr-registry-secret \
                --docker-server=982640051576.dkr.ecr.ap-northeast-2.amazonaws.com \
                --docker-username=AWS \
                --docker-password="$TOKEN" \
                --namespace=spring-dev --dry-run=client -o yaml | kubectl apply -f -
              echo "Done"
          restartPolicy: OnFailure
