apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-healthz-conf
  namespace: ingress-nginx
data:
  default.conf: |
    server {
      listen 80;
      location /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
      }
    }
