apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-healthz
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-healthz
  template:
    metadata:
      labels:
        app: dummy-healthz
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: dummy-healthz-conf