image:
  repository: 982640051576.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-ca-infra-registry
  tag: prod-v24.0.0-5fcb09
  pullPolicy: Always
imagePullSecrets:
- name: ecr-registry-secret
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
livenessProbe:
  httpGet:
    path: /monitoring-prod/health
    port: 9292
  initialDelaySeconds: 120
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /monitoring-prod/health
    port: 9292
  initialDelaySeconds: 120
  periodSeconds: 30
env:
- name: OTEL_RESOURCE_ATTRIBUTES
  value: "service.name={{ .Values.serviceName }},k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.cluster.name=ktb-ca-prod"
- name: POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: SPRING_PROFILES_ACTIVE
  value: "prod"
- name: JAVA_OPTS
  value: "-Xms512m -Xmx1024m"
- name: OTEL_SERVICE_NAME
  value: "spring-prod"
- name: CONTAINER_NAME
  value: "spring"
- name: AWS_REGION
  value: ap-northeast-2
javaOpts:
- "-javaagent:/otel-agent/otel-agent.jar"
- "-Dotel.service.name=${OTEL_SERVICE_NAME}"
- "-Dotel.exporter.otlp.endpoint=http://otel-collector.observability:4318"
- "-Dotel.instrumentation.spring-web.enabled=true"
- "-Dotel.instrumentation.http.enabled=true"
- "-Dotel.instrumentation.servlet.enabled=true"
- "-Dotel.instrumentation.jdbc.enabled=true"
- "-Dotel.instrumentation.kubernetes.enabled=true"
- "-Dotel.k8s.cluster.name=ktb-ca-prod"
- "-Dotel.k8s.namespace.name=${NAMESPACE}"
- "-Dotel.k8s.pod.name=${POD_NAME}"
- "-Dotel.k8s.container.name=${CONTAINER_NAME}"
- "-Dsun.net.inetaddr.ttl=30"
- "-Duser.timezone=Asia/Seoul"
service:
  type: ClusterIP
  port: 8080
  metricsPort: 9292
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: api.kakaotech.com
    paths:
    - path: /
      pathType: Prefix
otelAgent:
  s3Bucket: ktb-ca-mvp-static/otel
logging:
  persistence:
    enabled: false
    size: 10Gi
    storageClass: "gp2"
  retention:
    days: 30
