replicaCount: 2

image:
  repository: 982640051576.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-ca-infra-registry
  tag: development-v4.11.0-cf1723
  pullPolicy: Always

imagePullSecrets:
        - name: ecr-registry-secret

env:
  ENV : production

ingress: 
  enabled: true
  host: www.kakaotech.com
  
resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80