replicaCount: 2
image:
  repository: 982640051576.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-ca-infra-registry
  tag: production-v10.0.0-75afe2
  pullPolicy: Always
imagePullSecrets:
  - name: ecr-registry-secret
env:
  ENV: production
ingress:
  enabled: true
  hosts:
    - host: www.kakaotech.com
      paths:
        - path: /
          pathType: Prefix
    - host: kakaotech.com
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  type: ClusterIP
  port: 80
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
