image:
  repository: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/next-app
  tag: prod-20240617-a1b2c3
env:
  apiUrl: https://api.kakaotech.com
ingress:
  enabled: true
  host: www.kakaotech.com
