apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-access-rolebinding
  namespace: spring-prod
  annotations:
    argocd.argoproj.io/tracking-id: accounts:spring-prod/RoleBinding:spring-prod/ecr-access-rolebinding
subjects:
- kind: ServiceAccount
  name: ecr-access-sa
  namespace: spring-prod
roleRef:
  kind: Role
  name: ecr-access-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-access-rolebinding
  namespace: spring-dev
  annotations:
    argocd.argoproj.io/tracking-id: accounts:spring-dev/RoleBinding:spring-dev/ecr-access-rolebinding
subjects:
- kind: ServiceAccount
  name: ecr-access-sa
  namespace: spring-dev
roleRef:
  kind: Role
  name: ecr-access-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-access-rolebinding
  namespace: next-prod
  annotations:
    argocd.argoproj.io/tracking-id: accounts:next-prod/RoleBinding:next-prod/ecr-access-rolebinding
subjects:
- kind: ServiceAccount
  name: ecr-access-sa
  namespace: next-prod
roleRef:
  kind: Role
  name: ecr-access-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-access-rolebinding
  namespace: next-dev
  annotations:
    argocd.argoproj.io/tracking-id: accounts:next-dev/RoleBinding:next-dev/ecr-access-rolebinding
subjects:
- kind: ServiceAccount
  name: ecr-access-sa
  namespace: next-dev
roleRef:
  kind: Role
  name: ecr-access-role
  apiGroup: rbac.authorization.k8s.io
