replicaCount: 2

image:
  repository: 982640051576.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-ca-infra-registry
  tag: ysocket-prod
  pullPolicy: Always

imagePullSecrets:
- name: ecr-registry-secret

ingress:
  enabled: true
  host: www.kakaotech.com

service:
  type: ClusterIP
  port: 3002

websocket:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    terminationGracePeriodSeconds: 30

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /
    port: 3002
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 3002
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
