replicaCount: 2

image:
  repository: 982640051576.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-ca-infra-registry
  tag: ysocket-prod
  pullPolicy: Always

imagePullSecrets:
- name: ecr-registry-secret

ingress:
  enabled: false

service:
  type: NodePort
  port: 3002
  nodePort: 30082

websocket:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    terminationGracePeriodSeconds: 30

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
