apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          config:
            use-proxy-protocol: "true"
          ingress:         # ← 이 부분 추가
            enabled: false # ← 샘플 Ingress 리소스 비활성화
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
