apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accounts-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/20-real-gitops
    targetRevision: main
    path: system/accounts
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
