apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: 2.25.0
    helm:
      values: |
        controller:
          region: ap-northeast-2
        storageClasses:
          - name: gp2
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
            volumeBindingMode: WaitForFirstConsumer
            parameters:
              type: gp2
            reclaimPolicy: Delete
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
