apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.signoz.io
    chart: k8s-infra
    targetRevision: 0.13.0
    helm:
      values: |
        otelCollector:
          enabled: false

        signoz:
          otelCollectorEndpoint: otel-collector.observability.svc.cluster.local:4317

        infra:
          container:
            enabled: true
          host:
            enabled: true

          hostmetrics:
            enabled: true
            collection_interval: 30s
            receivers:
              - cpu
              - memory
              - disk
              - filesystem
              - network

          extraEnv:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector.observability.svc.cluster.local:4317
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
