apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: websocket-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/20-real-gitops
    targetRevision: main
    path: apps/base/websocket
    helm:
      valueFiles:
      - ../../../env/dev/websocket/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: websocket-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
