replicaCount: 1

image:
  repository: ktb-ca-infra-registry
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /monitoring-dev/health
    port: 9292
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /monitoring-dev/health
    port: 9292
  initialDelaySeconds: 30
  periodSeconds: 10

env:
- name: SPRING_PROFILES_ACTIVE
  value: "dev"
- name: JAVA_OPTS
  value: "-Xms256m -Xmx512m"
- name: OTEL_SERVICE_NAME
  value: "spring-dev"
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: CONTAINER_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.containers[0].name

javaOpts:
- "-javaagent:/otel-agent/otel-agent.jar"
- "-Dotel.service.name=${OTEL_SERVICE_NAME}"
- "-Dotel.exporter.otlp.endpoint=https://collector.kakaotech.com/"
- "-Dotel.instrumentation.spring-web.enabled=true"
- "-Dotel.instrumentation.http.enabled=true"
- "-Dotel.instrumentation.servlet.enabled=true"
- "-Dotel.instrumentation.jdbc.enabled=true"
- "-Dotel.instrumentation.kubernetes.enabled=true"
- "-Dotel.k8s.cluster.name=ktb-ca-dev"
- "-Dotel.k8s.namespace.name=${NAMESPACE}"
- "-Dotel.k8s.pod.name=${POD_NAME}"
- "-Dotel.k8s.container.name=${CONTAINER_NAME}"
- "-Duser.timezone=Asia/Seoul"

service:
  type: ClusterIP
  port: 8080
  metricsPort: 9292

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
  - host: api-dev.kakaotech.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: spring-dev-tls
    hosts:
    - api-dev.kakaotech.com

otelAgent:
  s3Bucket: your-bucket-name

logging:
  persistence:
    enabled: false
