replicaCount: 2

image:
  repository: ktb-ca-infra-registry
  tag: latest
  pullPolicy: Always

env:
  apiUrl: https://cadev.kakaotech.com

ingress: 
  enabled: true
  host: cadev.kakaotech.com
  
resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80