replicaCount: 2

image:
  repository: 982640051576.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-ca-infra-registry
  tag: development-v4.11.0-cf1723
  pullPolicy: Always

imagePullSecrets:
        - name: ecr-registry-secret

env:
  ENV : development

ingress: 
  enabled: true
  host: cadev.kakaotech.com
  
resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
    
livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80